### ISSUE TITLE
type piracy of Base.zero

### ISSUE THREAD

**Issue by marius311** [JuliaGNI/GeometricBase.jl#5]
Looks like this package [defines](https://github.com/JuliaGNI/GeometricBase.jl/blob/e8797bf29586efb2ecf40aa20975d0649379ddec/src/types.jl#L70) `Base.zero(::AbstractVector{<:Number})` which is type piracy and probably shouldn't happen. I ran into this as it broke `zero` of some custom AbstractArray I had after loading the RungeKutta package (which depends on this).

**Comment by michakraus** [comment]
@marius311 Thanks for pointing this out and apologies for looking into this so late. It seems the GitHub notification of your issue somehow went under the radar.

This is fixed now and I will trigger a new release asap. However, it may take a few days until this propagated into all the other packages.
